// <auto-generated />
using System;
using JogoAdivinha.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace JogoAdivinha.Migrations
{
    [DbContext(typeof(Contexto))]
    partial class ContextoModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.0");

            modelBuilder.Entity("JogoAdivinha.Models.Historico", b =>
                {
                    b.Property<int>("COD_JOGADOR")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("NUM_TENTATIVA")
                        .HasColumnType("INTEGER");

                    b.Property<string>("RESULTADO")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Tentativa")
                        .HasColumnType("TEXT");

                    b.HasKey("COD_JOGADOR");

                    b.ToTable("Historicos");
                });
#pragma warning restore 612, 618
        }
    }
}
